name: Release Management

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Release Notes generieren
        id: changelog
        run: |
          echo "## Changelog" > changelog.md
          git log -1 --pretty=format:"%h %s" >> changelog.md

      - name: Release veröffentlichen
        uses: softprops/action-gh-release@v2
        with:
          files: |
            changelog.md
          body_path: changelog.md
